/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    EchartRadar: typeof import('./src/components/echarts/EchartRadar.vue')['default']
    EchartsBar: typeof import('./src/components/echarts/EchartsBar.vue')['default']
    EchartsBing: typeof import('./src/components/echarts/EchartsBing.vue')['default']
    EchartsLine: typeof import('./src/components/echarts/EchartsLine.vue')['default']
    EchartsMap: typeof import('./src/components/echarts/EchartsMap.vue')['default']
    EchartsMap2: typeof import('./src/components/echarts/EchartsMap2.vue')['default']
    EchartsMap3: typeof import('./src/components/echarts/EchartsMap3.vue')['default']
    MenuAside: typeof import('./src/components/layout/MenuAside.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubComponentOne: typeof import('./src/components/subComponentsTest/SubComponentOne.vue')['default']
    TDTMap: typeof import('./src/components/TdtMap/src/TDTMap.vue')['default']
    TDTMapInfoWindow: typeof import('./src/components/TdtMap/src/TDTMapInfoWindow.vue')['default']
    TDTMapSinglePoint: typeof import('./src/components/TdtMap/src/TDTMapSinglePoint.vue')['default']
  }
}
