import 'ant-design-vue/es/button/style/css'
import 'ant-design-vue/es/table/style/css'
import 'ant-design-vue/es/input/style/css'
import 'ant-design-vue/es/date-picker/style/css'
import 'ant-design-vue/es/tabs/style/css'
import 'ant-design-vue/es/carousel/style/css'
import 'ant-design-vue/es/table/style/css'
